// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkx7DeEkhxXwJgJRKIlyFpkXri4D8NzQ',
    appId: '1:981909531002:ios:efe1bc6f925105ad3f0ec3',
    messagingSenderId: '981909531002',
    projectId: 'rishu-attendance-2025',
    storageBucket: 'rishu-attendance-2025.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkx7DeEkhxXwJgJRKIlyFpkXri4D8NzQ',
    appId: '1:981909531002:ios:efe1bc6f925105ad3f0ec3',
    messagingSenderId: '981909531002',
    projectId: 'rishu-attendance-2025',
    storageBucket: 'rishu-attendance-2025.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7STVghl9L24fYkO9HeOv7kesW70i0',
    appId: '1:981909531002:web:429a9e0f0d0e1c8c3f0ec3',
    messagingSenderId: '981909531002',
    projectId: 'rishu-attendance-2025',
    authDomain: 'rishu-attendance-2025.firebaseapp.com',
    storageBucket: 'rishu-attendance-2025.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5d7STVghl9L24fYkO9HeOv7kesW70i0',
    appId: '1:981909531002:web:429a9e0f0d0e1c8c3f0ec3',
    messagingSenderId: '981909531002',
    projectId: 'rishu-attendance-2025',
    authDomain: 'rishu-attendance-2025.firebaseapp.com',
    storageBucket: 'rishu-attendance-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwuCkz8XqUNURHfxrVKhSizD0XcPgrpBY',
    appId: '1:981909531002:android:eaa56ad2eef879883f0ec3',
    messagingSenderId: '981909531002',
    projectId: 'rishu-attendance-2025',
    storageBucket: 'rishu-attendance-2025.firebasestorage.app',
  );

}